### ISSUE TITLE
Azure setup fails

### ISSUE THREAD

**Issue by tornizanQ** [QualiSystems/Azure-Shell#145]
str
Have a blueprint with azure app in it
reserve the blueprint

BIR
Error appears 
 General
Description: Failed to wait for the command execution to end:
Command execution failed with 'Script runner exited with exit code: 1' error.
Traceback (most recent call last):
  File "C:\Work\Trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Work\Trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\tor.n\AppData\Local\Temp\203892b6-74f0-4cca-9b1f-4617798ff6a6\Default Sandbox Setup.zip\__main__.py", line 8, in 
  File "C:\Users\tor.n\AppData\Local\Temp\203892b6-74f0-4cca-9b1f-4617798ff6a6\Default Sandbox Setup.zip\__main__.py", line 5, in main
  File "C:\Users\tor.n\AppData\Local\Temp\203892b6-74f0-4cca-9b1f-4617798ff6a6\Default Sandbox Setup.zip\sandbox_scripts\profiler\env_profiler.py", line 13, in wrapper
  File "C:\Users\tor.n\AppData\Local\Temp\203892b6-74f0-4cca-9b1f-4617798ff6a6\Default Sandbox Setup.zip\sandbox_scripts\environment\setup\setup_script.py", line 26, in execute
  File "C:\Work\Trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\site-packages\cloudshell\helpers\scripts\cloudshell_scripts_helpers.py", line 25, in get_api_session
    env_details['domain'])
  File "C:\Work\Trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\site-packages\cloudshell\api\cloudshell_api.py", line 1690, in __init__
    response_info = self.Logon(username, password, domain)
  File "C:\Work\Trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\site-packages\cloudshell\api\cloudshell_api.py", line 3036, in Logon
    return self.generateAPIRequest(OrderedDict([('method_name', 'Logon'), ('username', username), ('password', password), ('domainName', domainName)]))
  File "C:\Work\Trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\site-packages\cloudshell\api\common_cloudshell_api.py", line 390, in generateAPIRequest
    response_str = self._sendRequest(self.username, self.domain, method_name, request_str)
  File "C:\Work\Trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\site-packages\cloudshell\api\cloudshell_api.py", line 1706, in _sendRequest
    return CommonAPISession._sendRequest(self, operation, message, request_headers)
  File "C:\Work\Trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\site-packages\cloudshell\api\common_cloudshell_api.py", line 329, in _sendRequest
    response = urllib23.urlopen(request_object)
  File "C:\Work\Trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Work\Trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\urllib2.py", line 431, in open
    response = self._open(req, data)
  File "C:\Work\Trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\urllib2.py", line 449, in _open
    '_open', req)
  File "C:\Work\Trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "C:\Work\Trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\urllib2.py", line 1227, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "C:\Work\Trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\urllib2.py", line 1197, in do_open
    raise URLError(err)
urllib2.URLError: 

Parameters:

**Comment by tornizanQ** [comment]
8029 Port was occupied by some java process
