### ISSUE TITLE
Concurrent prepare connectivity processes fail creating subnets

### ISSUE THREAD

**Issue by igoro1975** [QualiSystems/Azure-Shell#152]
Prepare connectivity process fails when the other prepare connectivity process trying to create a subnet.

See the details:
2016-11-13 13:02:21,609 - application - InstanceLoader - ERROR - Customer's driver raised an exception:
Traceback (most recent call last):
  File "C:\TFS\QualiSystems\Trunk\Drop\TestShell\ExecutionServer\QsPythonDriverHost\execution\instance_loader.py", line 134, in invoke_func
    result = driver_func(**args)
  File "C:\Work\Git\Azure-Shell\drivers\azure_shell\driver.py", line 38, in PrepareConnectivity
    return self.azure_shell.prepare_connectivity(context, request)
  File "c:\work\git\azure-shell\package\cloudshell\cp\azure\azure_shell.py", line 140, in prepare_connectivity
    request=prepare_connectivity_request)
  File "c:\work\git\azure-shell\package\cloudshell\cp\azure\domain\vm_management\operations\prepare_connectivity_operation.py", line 139, in prepare_connectivity
    wait_for_result=True)
  File "c:\work\git\azure-shell\package\cloudshell\cp\azure\domain\services\network_service.py", line 213, in create_subnet
    result.wait()
  File "C:\TFS\QualiSystems\Trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\site-packages\msrestazure\azure_operation.py", line 526, in wait
    raise self._exception
CloudError: Azure Error: AnotherOperationInProgress
Message: Another operation on this or dependent resource is in progress. To retrieve status of the operation use uri: https://management.azure.com/subscriptions/533d31a2-915f-44aa-9807-e2a1cb89b60e/providers/Microsoft.Network/locations/westeurope/operations/f341dfda-d321-4d88-822d-7cde1a3208be?api-version=2016-06-01.

**Comment by alexazarh** [comment]
We need to check if this error can also happen during teardown when deleting the subnte
