### ISSUE TITLE
Fail to deploy when there are no tags on the managment network

### ISSUE THREAD

**Issue by TomerAdmon** [QualiSystems/Azure-Shell#182]
2016-11-22 16:40:32,119 [INFO]: QS.Azure qs_logger - log_execution_info   --------------- Execution Info: ---------------------------
2016-11-22 16:40:32,119 [INFO]: QS.Azure qs_logger - log_execution_info   Username            : admin
2016-11-22 16:40:32,119 [INFO]: QS.Azure qs_logger - log_execution_info   Operating System    : Windows-8-6.2.9200
2016-11-22 16:40:32,121 [INFO]: QS.Azure qs_logger - log_execution_info   Description         : Blueprint with preconfigured setup & teardown processes.Deploys Apps and resolves connections on Setup, and deletes App VMs on Teardown
2016-11-22 16:40:32,121 [INFO]: QS.Azure qs_logger - log_execution_info   Python version      : 2.7.10
2016-11-22 16:40:32,121 [INFO]: QS.Azure qs_logger - log_execution_info   IP                  : 192.168.30.104
2016-11-22 16:40:32,121 [INFO]: QS.Azure qs_logger - log_execution_info   Hostname            : QS-IL-TOMERAD
2016-11-22 16:40:32,121 [INFO]: QS.Azure qs_logger - log_execution_info   Platform            : Windows
2016-11-22 16:40:32,121 [INFO]: QS.Azure qs_logger - log_execution_info   ReservationID       : 1c316307-9ebc-4c71-a5a2-d0d9719b72dd
2016-11-22 16:40:32,121 [INFO]: QS.Azure qs_logger - log_execution_info   EnviromentName      : Azure - Single machine
2016-11-22 16:40:32,122 [INFO]: QS.Azure qs_logger - log_execution_info   -----------------------------------------------------------
2016-11-22 16:40:32,122 [INFO]: QS.Azure qs_logger - log_execution_info   
2016-11-22 16:40:32,122 [INFO]: QS.Azure azure_shell - prepare_connectivity Preparing Connectivity for Azure VM
2016-11-22 16:40:32,131 [INFO]: QS.Azure prepare_connectivity_operation - prepare_connectivity Creating a resource group: 1c316307-9ebc-4c71-a5a2-d0d9719b72dd .
2016-11-22 16:40:32,693 [INFO]: QS.Azure prepare_connectivity_operation - prepare_connectivity Creating a storage account 1c3163079ebc4c71a5a2d0d9 .
2016-11-22 16:40:51,766 [INFO]: QS.Azure prepare_connectivity_operation - _create_key_pair     Creating a Key pair for the sandbox.
2016-11-22 16:40:58,148 [ERROR]: QS.Azure error_handling_context - __exit__             Error occurred: Traceback (most recent call last):
2016-11-22 16:40:58,148 [ERROR]: QS.Azure error_handling_context - __exit__               File "C:\Work\Branches\7.1\Drop\TestShell\ExecutionServer\python\2.7.10\lib\site-packages\cloudshell\cp\azure\azure_shell.py", line 167, in prepare_connectivity
2016-11-22 16:40:58,148 [ERROR]: QS.Azure error_handling_context - __exit__                 request=prepare_connectivity_request)
2016-11-22 16:40:58,148 [ERROR]: QS.Azure error_handling_context - __exit__               File "C:\Work\Branches\7.1\Drop\TestShell\ExecutionServer\python\2.7.10\lib\site-packages\cloudshell\cp\azure\domain\vm_management\operations\prepare_connectivity_operation.py", line 90, in prepare_connectivity
2016-11-22 16:40:58,148 [ERROR]: QS.Azure error_handling_context - __exit__                 tags_service=self.tags_service)
2016-11-22 16:40:58,148 [ERROR]: QS.Azure error_handling_context - __exit__               File "C:\Work\Branches\7.1\Drop\TestShell\ExecutionServer\python\2.7.10\lib\site-packages\cloudshell\cp\azure\domain\services\network_service.py", line 344, in get_virtual_network_by_tag
2016-11-22 16:40:58,148 [ERROR]: QS.Azure error_handling_context - __exit__                 None)
2016-11-22 16:40:58,148 [ERROR]: QS.Azure error_handling_context - __exit__               File "C:\Work\Branches\7.1\Drop\TestShell\ExecutionServer\python\2.7.10\lib\site-packages\cloudshell\cp\azure\domain\services\network_service.py", line 343, in <genexpr>
2016-11-22 16:40:58,148 [ERROR]: QS.Azure error_handling_context - __exit__                 network and tags_service.try_find_tag(tags_list=network.tags, tag_key=tag_key) == tag_value),
2016-11-22 16:40:58,148 [ERROR]: QS.Azure error_handling_context - __exit__               File "C:\Work\Branches\7.1\Drop\TestShell\ExecutionServer\python\2.7.10\lib\site-packages\cloudshell\cp\azure\domain\services\tags.py", line 51, in try_find_tag
2016-11-22 16:40:58,148 [ERROR]: QS.Azure error_handling_context - __exit__                 return next((tags_list[key] for key in tags_list.keys() if key == tag_key), None)
2016-11-22 16:40:58,148 [ERROR]: QS.Azure error_handling_context - __exit__             AttributeError: 'NoneType' object has no attribute 'keys'
2016-11-22 16:40:58,148 [ERROR]: QS.Azure error_handling_context - __exit__

**Comment by tornizanQ** [comment]
Is this error is better?
Error: General
Description: Failed to wait for the command execution to end:
Command execution failed with 'Script runner exited with exit code: 1' error.
2016-12-01 09:52:38,252 [INFO]: Setup.CloudShell_Sandbox_Setup setup_script - _prepare_connectivity Preparing connectivity for reservation 46cb57dc-f82e-437e-831c-6fb0d30af5a4
Traceback (most recent call last):
  File "C:\Work\Branches\7.1\Drop\TestShell\ExecutionServer\python\2.7.10\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Work\Branches\7.1\Drop\TestShell\ExecutionServer\python\2.7.10\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\tor.n\AppData\Local\Temp\092b59cb-89f5-42b7-8445-91d339e3340e\Default Sandbox Setup.zip\__main__.py", line 8, in 
  File "C:\Users\tor.n\AppData\Local\Temp\092b59cb-89f5-42b7-8445-91d339e3340e\Default Sandbox Setup.zip\__main__.py", line 5, in main
  File "C:\Users\tor.n\AppData\Local\Temp\092b59cb-89f5-42b7-8445-91d339e3340e\Default Sandbox Setup.zip\sandbox_scripts\profiler\env_profiler.py", line 13, in wrapper
  File "C:\Users\tor.n\AppData\Local\Temp\092b59cb-89f5-42b7-8445-91d339e3340e\Default Sandbox Setup.zip\sandbox_scripts\environment\setup\setup_script.py", line 32, in execute
  File "C:\Users\tor.n\AppData\Local\Temp\092b59cb-89f5-42b7-8445-91d339e3340e\Default Sandbox Setup.zip\sandbox_scripts\environment\setup\setup_script.py", line 69, in _prepare_connectivity
  File "C:\Work\Branches\7.1\Drop\TestShell\ExecutionServer\python\2.7.10\lib\site-packages\cloudshell\api\cloudshell_api.py", line 2432, in PrepareSandboxConnectivity
    return self.generateAPIRequest(OrderedDict([('method_name', 'PrepareSandboxConnectivity'), ('reservationId', reservationId)]))
  File "C:\Work\Branches\7.1\Drop\TestShell\ExecutionServer\python\2.7.10\lib\site-packages\cloudshell\api\common_cloudshell_api.py", line 398, in generateAPIRequest
    raise CloudShellAPIError(api_result.error_code, api_result.error, response_str)
cloudshell.api.common_cloudshell_api.CloudShellAPIError: CloudShell API error 100: Error preparing connectivity in reservation '46cb57dc-f82e-437e-831c-6fb0d30af5a4'. Error: Failed executing prepare connectivity command. Error: Could not find Management Virtual Network in Azure.
