### ISSUE TITLE
rollback faild in deploy - missing arguments for function

### ISSUE THREAD

**Issue by TomerAdmon** [QualiSystems/Azure-Shell#183]
2016-11-22 17:05:46,424 [INFO]: QS.Azure qs_logger - log_execution_info   --------------- Execution Info: ---------------------------
2016-11-22 17:05:46,424 [INFO]: QS.Azure qs_logger - log_execution_info   Username            : admin
2016-11-22 17:05:46,424 [INFO]: QS.Azure qs_logger - log_execution_info   Operating System    : Windows-8-6.2.9200
2016-11-22 17:05:46,424 [INFO]: QS.Azure qs_logger - log_execution_info   Description         : Blueprint with preconfigured setup & teardown processes.Deploys Apps and resolves connections on Setup, and deletes App VMs on Teardown
2016-11-22 17:05:46,424 [INFO]: QS.Azure qs_logger - log_execution_info   Python version      : 2.7.10
2016-11-22 17:05:46,424 [INFO]: QS.Azure qs_logger - log_execution_info   IP                  : 192.168.30.75
2016-11-22 17:05:46,424 [INFO]: QS.Azure qs_logger - log_execution_info   Hostname            : QS-IL-TOMERAD
2016-11-22 17:05:46,426 [INFO]: QS.Azure qs_logger - log_execution_info   Platform            : Windows
2016-11-22 17:05:46,426 [INFO]: QS.Azure qs_logger - log_execution_info   ReservationID       : d13acb5f-c69c-4c72-982a-4864e7a12583
2016-11-22 17:05:46,426 [INFO]: QS.Azure qs_logger - log_execution_info   EnviromentName      : Azure - Single machine
2016-11-22 17:05:46,426 [INFO]: QS.Azure qs_logger - log_execution_info   -----------------------------------------------------------
2016-11-22 17:05:46,426 [INFO]: QS.Azure qs_logger - log_execution_info   
2016-11-22 17:05:46,427 [INFO]: QS.Azure azure_shell - prepare_connectivity Preparing Connectivity for Azure VM
2016-11-22 17:05:46,427 [INFO]: QS.Azure prepare_connectivity_operation - prepare_connectivity Creating a resource group: d13acb5f-c69c-4c72-982a-4864e7a12583 .
2016-11-22 17:05:46,904 [INFO]: QS.Azure prepare_connectivity_operation - prepare_connectivity Creating a storage account d13acb5fc69c4c72982a4864 .
2016-11-22 17:06:06,141 [INFO]: QS.Azure prepare_connectivity_operation - _create_key_pair     Creating a Key pair for the sandbox.
2016-11-22 17:06:10,743 [INFO]: QS.Azure prepare_connectivity_operation - prepare_connectivity Creating a network security group 'd13acb5fc69c4c72982a4864' .
2016-11-22 17:06:22,588 [INFO]: QS.Azure prepare_connectivity_operation - prepare_connectivity Received CIDR 10.0.1.0/24 from server
2016-11-22 17:06:22,588 [INFO]: QS.Azure prepare_connectivity_operation - _create_subnet       Creating a subnet d13acb5f-c69c-4c72-982a-4864e7a12583 under: CloudShellManagement/CloudShellSandbox.
2016-11-22 17:07:27,493 [INFO]: QS.Azure azure_shell - deploy_azure_vm      Deploying Azure VM
2016-11-22 17:07:40,904 [ERROR]: QS.Azure error_handling_context - __exit__             Error occurred: Traceback (most recent call last):
2016-11-22 17:07:40,904 [ERROR]: QS.Azure error_handling_context - __exit__               File "C:\Work\Branches\7.1\Drop\TestShell\ExecutionServer\python\2.7.10\lib\site-packages\cloudshell\cp\azure\azure_shell.py", line 99, in deploy_azure_vm
2016-11-22 17:07:40,904 [ERROR]: QS.Azure error_handling_context - __exit__                 logger=logger)
2016-11-22 17:07:40,904 [ERROR]: QS.Azure error_handling_context - __exit__               File "C:\Work\Branches\7.1\Drop\TestShell\ExecutionServer\python\2.7.10\lib\site-packages\cloudshell\cp\azure\domain\vm_management\operations\deploy_operation.py", line 364, in deploy
2016-11-22 17:07:40,904 [ERROR]: QS.Azure error_handling_context - __exit__                 ip_name=ip_name)
2016-11-22 17:07:40,904 [ERROR]: QS.Azure error_handling_context - __exit__             TypeError: _rollback_deployed_resources() takes exactly 7 arguments (6 given)
2016-11-22 17:07:40,904 [ERROR]: QS.Azure error_handling_context - __exit__

**Comment by TomerAdmon** [comment]
******Make sure to add unit-test for this!
