### ISSUE TITLE
Marketplace image failed to deploy

### ISSUE THREAD

**Issue by TomerAdmon** [QualiSystems/Azure-Shell#234]
STR:
deploy a jenkins app from a Sandbox.

Image information:
Publisher: cloudbees    
Offer: jenkins-enterprise       
Sku: jenkins-enterprise
![image](https://cloud.githubusercontent.com/assets/12639815/20969834/6e32e65e-bc93-11e6-8eb3-97d483534c85.png)

result:
![image](https://cloud.githubusercontent.com/assets/12639815/20969823/68f2a9a4-bc93-11e6-9e74-d247d486e8f4.png)

**Comment by TomerAdmon** [comment]
2016-12-07 15:09:13,796 [INFO]: QS.Azure_VM driver - Deploy               Deploy started
2016-12-07 15:10:57,168 [ERROR]: QS.Azure_VM error_handling_context - __exit__             Error occurred: Traceback (most recent call last):
2016-12-07 15:10:57,168 [ERROR]: QS.Azure_VM error_handling_context - __exit__               File "c:\users\tomer.a\appdata\local\temp\tmposnwwu.zip_env\driver.py", line 49, in Deploy
2016-12-07 15:10:57,168 [ERROR]: QS.Azure_VM error_handling_context - __exit__                 False)
2016-12-07 15:10:57,168 [ERROR]: QS.Azure_VM error_handling_context - __exit__               File "C:\Work\Branches\7.1\Drop\TestShell\ExecutionServer\python\2.7.10\lib\site-packages\cloudshell\api\cloudshell_api.py", line 2535, in ExecuteCommand
2016-12-07 15:10:57,168 [ERROR]: QS.Azure_VM error_handling_context - __exit__                 return self.generateAPIRequest(OrderedDict([('method_name', 'ExecuteCommand'), ('reservationId', reservationId), ('targetName', targetName), ('targetType', targetType), ('commandName', commandName), ('commandInputs', CommonAPIRequest.toContainer(commandInputs)), ('printOutput', printOutput)]))
2016-12-07 15:10:57,168 [ERROR]: QS.Azure_VM error_handling_context - __exit__               File "C:\Work\Branches\7.1\Drop\TestShell\ExecutionServer\python\2.7.10\lib\site-packages\cloudshell\api\common_cloudshell_api.py", line 398, in generateAPIRequest
2016-12-07 15:10:57,168 [ERROR]: QS.Azure_VM error_handling_context - __exit__                 raise CloudShellAPIError(api_result.error_code, api_result.error, response_str)
2016-12-07 15:10:57,168 [ERROR]: QS.Azure_VM error_handling_context - __exit__             CloudShellAPIError: CloudShell API error 104: Command execution failed with error: 'CloudError'.
2016-12-07 15:10:57,168 [ERROR]: QS.Azure_VM error_handling_context - __exit__             Error description: Azure Error: VMMarketplaceInvalidInput
2016-12-07 15:10:57,168 [ERROR]: QS.Azure_VM error_handling_context - __exit__             Message: Creating a virtual machine from Marketplace image requires Plan information in the request. OS disk name is ad6e43d8a28f47529fe4b85b.
2016-12-07 15:10:57,168 [ERROR]: QS.Azure_VM error_handling_context - __exit__

**Comment by igoro1975** [comment]
Confluence page should be created.

**Comment by TomerAdmon** [comment]
We will need to add documentation for that one...

**Comment by TomerAdmon** [comment]
@igoro1975  - please add the confluence page link :-)

**Comment by TomerAdmon** [comment]
This issue refers to images from the market place that include software  in them so the user will pay for the software in additional to the machine price. In those scenarios, the user should accept the additional cost by  following  the procedure described in the confluence page Igor created.

**Comment by yairbb** [comment]
@igoro1975 

Hi Igor 

could you send a link to the confluence page ?

**Comment by Shnitselon** [comment]
note explaining how to enable programmatic deployment in online help's "Managing Apps" topic>"Azure VM From Marketplace" deployment type
