### ISSUE TITLE
Creating 20 custom image apps results in some failures due to invalid passwords

### ISSUE THREAD

**Issue by TaiTheGreat** [QualiSystems/Azure-Shell#266]
1. Create a brand new custom image app, and do not touch the username / password attributes. 
2. Add 20 of these apps to a reservation. 
3. Reserve. 

BIR if one or more fail on account of an invalid password (error below).

2016-12-14 16:10:23,741 [65] ERROR ResourceManager.TclAPI - [IP: ::1, Machine: QS-IL-TAI:8029 - Tcl, QualiSystems Username: admin]
RemoveDeployedCommandException [Error Code: General] [Original Time: 2016-12-14 16:10:23,741]: Could not delete the following resources: azurecustom13681bd3d5,azurecustom128e388142,azurecustom2c796397a,azurecustom900b99e3d,azurecustom3d6615eaa,azurecustom85916b745,azurecustom4f85bcc65
   at QualiSystems.ResourceManagement.Service.DomainService.Reservation.ReservationDomainService.RemoveDeployedResource(Reservation reservation, Guid[] deployedResourcesToRemove)
   at QualiSystems.ResourceManagement.Service.Domain.ReservationApplicationService.RemoveDeployedResourceFromReservation(Guid reservationId, Guid[] deployedResourcesToRemove)
   at QualiSystems.ResourceManagement.Service.Api.Plugin.Interfaces.ReservationAPIApplicationService.RemoveResourcesFromReservation(Guid reservationId, String[] resourcesFullName)
2016-12-14 16:27:53,169 [66] ERROR ResourceManager.TclAPI - CloudShellAPIError: Command execution failed with error: 'CloudError'.
Error description: Azure Error: InvalidParameter
Message: The supplied password must be between 6-72 characters long and must satisfy at least 3 of password complexity requirements from the following: 
1) Contains an uppercase character
2) Contains a lowercase character
3) Contains a numeric digit
4) Contains a special character.
Target: adminPassword
2016-12-14 16:27:53,169 [66] ERROR ResourceManager.TclAPI - QS.TestShell.Server.ResourceManagement.Plugins.ApiPlugin.InternalApiException: CloudShellAPIError: Command execution failed with error: 'CloudError'.
Error description: Azure Error: InvalidParameter
Message: The supplied password must be between 6-72 characters long and must satisfy at least 3 of password complexity requirements from the following: 
1) Contains an uppercase character
2) Contains a lowercase character
3) Contains a numeric digit
4) Contains a special character.
Target: adminPassword
   at QS.TestShell.Server.ResourceManagement.Plugins.ApiPlugin.Interfaces.AppAPIApplicationService.DeployAppBarebones(Guid reservationId, String appName, InputNameValue[] commandInputs, Boolean printOutput, Boolean bulkStatusAndVersionUpdate)
   at QS.TestShell.Server.ResourceManagement.Plugins.ApiPlugin.Interfaces.AppAPIApplicationService.<>c__DisplayClass12.<>c__DisplayClass17.<DeployAppToCloudProviderBulk>b__d()

**Comment by apiddubny** [comment]
It's needed to fix password generating in VMCredentialsService_generate_password
Each password must have several digit/uppercase/lowercase symbols for Windows VMs
