### ISSUE TITLE
When trying to cancel deployment of 10 apps from costume image the reservation subnet sometimes can stay live

### ISSUE THREAD

**Issue by tornizanQ** [QualiSystems/Azure-Shell#336]
STR
1. Have an environment with 10 azure apps from costume image 
2. Reserve the environment
3. Wait until the VMs has been created in azures portal resource group
4. before the vms has deployed in the reservation, End the reservation 
5. Wait for the tear down to finish 

BIR **unstable 2/3**
The subnet of the reservation hasn't been deleted.

Error from the activity feed:
Error: Script runner exited with exit code: 1
Description: Traceback (most recent call last):
  File "C:\Work\Branches\7.1\Drop\TestShell\ExecutionServer\python\2.7.10\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Work\Branches\7.1\Drop\TestShell\ExecutionServer\python\2.7.10\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\tor.n\AppData\Local\Temp\f1d47d2f-43d9-4561-a9e7-f592c68c071b\Default Sandbox Teardown.zip\__main__.py", line 8, in 
  File "C:\Users\tor.n\AppData\Local\Temp\f1d47d2f-43d9-4561-a9e7-f592c68c071b\Default Sandbox Teardown.zip\__main__.py", line 5, in main
  File "C:\Users\tor.n\AppData\Local\Temp\f1d47d2f-43d9-4561-a9e7-f592c68c071b\Default Sandbox Teardown.zip\sandbox_scripts\profiler\env_profiler.py", line 13, in wrapper
  File "C:\Users\tor.n\AppData\Local\Temp\f1d47d2f-43d9-4561-a9e7-f592c68c071b\Default Sandbox Teardown.zip\sandbox_scripts\environment\teardown\teardown_script.py", line 33, in execute
  File "C:\Users\tor.n\AppData\Local\Temp\f1d47d2f-43d9-4561-a9e7-f592c68c071b\Default Sandbox Teardown.zip\sandbox_scripts\environment\teardown\teardown_script.py", line 187, in _cleanup_connectivity
  File "C:\Work\Branches\7.1\Drop\TestShell\ExecutionServer\python\2.7.10\lib\site-packages\cloudshell\api\cloudshell_api.py", line 2442, in CleanupSandboxConnectivity
    return self.generateAPIRequest(OrderedDict([('method_name', 'CleanupSandboxConnectivity'), ('reservationId', reservationId)]))
  File "C:\Work\Branches\7.1\Drop\TestShell\ExecutionServer\python\2.7.10\lib\site-packages\cloudshell\api\common_cloudshell_api.py", line 398, in generateAPIRequest
    raise CloudShellAPIError(api_result.error_code, api_result.error, response_str)
cloudshell.api.common_cloudshell_api.CloudShellAPIError: CloudShell API error 100: Error cleaning connectivity in reservation '58064c50-464a-4bd5-abff-605afef81767'. Error: Failed executing cleanup connectivity command. Error: CleanupConnectivity ended with the error(s): [u'Subnet 58064c50-464a-4bd5-abff-605afef81767 is in use by /subscriptions/4455e4ef-c725-4119-885f-fd837d9629cc/resourceGroups/58064c50-464a-4bd5-abff-605afef81767/providers/Microsoft.Network/networkInterfaces/azurecus93643f428ace42e2/ipConfigurations/default and cannot be deleted.']

Parameters:

Logs

[Microsoft_Azure--01-Jan-2017--15-39-42.zip](https://github.com/QualiSystems/Azure-Shell/files/680008/Microsoft_Azure--01-Jan-2017--15-39-42.zip)

**Comment by tornizanQ** [comment]
Also occurs with 1 app from market
